lr: 0.0005
batch_size: 4
num_epochs: 10

train_paths:
  - "C:/Users/parkminhyuk/Downloads/ai-pro/open/data/train"

val_paths:
  - "C:/Users/parkminhyuk/Downloads/ai-pro/open/data/validation"

input_mode: "rgb"
checkpoint_filename: "rgb_model"

early_stopping_patience: 4
monitor_metric: "val_loss"
monitor_mode: "min"
log_every_n_steps: 1
logger: false